### ISSUE TITLE
`flutter run` shows an error: "Invalid argument(s): Failed to load dynamic library"

### ISSUE THREAD

**Issue by paapu88** [josxha/dart_mbtiles#3]
Dear Developers,
I issue flutter run on my ubuntu 23.04 
```
cd ~/tmp
git clone git@github.com:josxha/dart_mbtiles.git
cd ./dart_mbtiles/example
flutter run
```

for android I get white screen on android
and error
`E/flutter ( 4902): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'assets/android/sqlite3': dlopen failed: library "assets/android/sqlite3" not found`

I could not find such a directory in this repo.

If one runs with Linux emulator instead of real android device error looks like:
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'assets/linux/sqlite3': assets/linux/sqlite3: cannot dynamically load position-independent executable
`

**Comment by josxha** [comment]
Hi @paapu88, `mbtiles` is a dart package. I added a simple dart example but full flutter app.

If you want to use the package with flutter the easiest integration is to add `sqlite3_flutter_libs` as a dependency to your pubspec.yaml like it's mentioned in the README.md:
```yaml
dependencies:
  mbtiles: ^0.4.0
  sqlite3_flutter_libs: ^0.5.18
```

To run the dart program, you should use `dart run` instead of `flutter run`. I haven't tested it for linux though so it could be that the sqlite path needs to be adjusted. Pull requests are welcome in case you are insterested.

**Comment by josxha** [comment]
While updating the documentation i tried to run `flutter run` myself. The actual error message in the console is:
```console
No supported devices connected.

The following devices were found, but are not supported by this project:
[...]
If you would like your app to run on web or windows, consider running `flutter create .` to generate projects for these platforms.
```

This is the expected error message since the example has no flutter support. 
@paapu88 Could it be that you ran `flutter create` in between?
